services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: production
        container_name: bvp-brain-api
        working_dir: /usr/src/app
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        ports:
            - '3000:3000'
        restart: always
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: my-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /etc/letsencrypt/live/brain-v2.bessemer.io/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/brain-v2.bessemer.io/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
        restart: always
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
