services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            # Argumentos de build para produção se necessário
            args:
                NODE_ENV: production
        container_name: bvp-brain-api
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        ports:
            - '3000:3000'
        restart: always
