services:
    # nginx:
    #     image: nginx:latest
    #     container_name: my-nginx
    #     ports:
    #         - '80:80'
    #         - '443:443'
    #     volumes:
    #         - /etc/letsencrypt/live/brain-gateway.bessemer.io/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
    #         - /etc/letsencrypt/live/brain-gateway.bessemer.io/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    #         - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #     depends_on:
    #         - api
    #     restart: always

    api:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: production
        container_name: bvp-brain-api
        working_dir: /usr/src/app
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        ports:
            - '3000:3000'
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
                reservations:
                    cpus: '0.5'
                    memory: 512M
        healthcheck:
            test: ['CMD', 'wget', '--spider', 'http://localhost:3000/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
